### ISSUE TITLE
Horizontal Lists 

### ISSUE THREAD

**Issue by imjoshdean-tc** [bvaughn/react-window#168]
Very similar to https://github.com/bvaughn/react-window/issues/158

I'm looking to potentially use this package to lazy load search results in an ecommerce platform that currently renders the results with a CSS grid in order to maximize the number of results on a row with the following CSS

```css
.grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(175px, 1fr));
}
```

is there some way to achieve this with `react-widow` that I might be missing? To be clear, I'm looking for a way to fill the width of the parent with as many items as possible before wrapping it onto the next line, very similar to how CSS grids render out columns.

Thanks!
