### ISSUE TITLE
How do I style the scroll bar

### ISSUE THREAD

**Issue by Hahahahx** [bvaughn/react-window#506]
![image](https://user-images.githubusercontent.com/45379017/90303169-6e213f00-dede-11ea-9c8e-74792f6be798.png)
I set it but it doesn't work

**Comment by taksenov** [comment]
Solution for Chrome, but maybe you can use FireFox prefixes too.

**js**

```js
import { VariableSizeList as List } from 'react-window';
import cx from 'classnames';

import styles from './ololo.module.scss';

// ...

<List className={cx(styles.customScrollBar)}>
  {Message}
</List>
```

**scss**

```scss
.customScrollBar {
  overflow-y: scroll;

  &::-webkit-scrollbar-track {
    box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.1);
    -webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.1);
    background-color: #f5f5f5;
  }

  &::-webkit-scrollbar {
    width: 6px;
    background-color: #f5f5f5;
  }

  &::-webkit-scrollbar-thumb {
    background-color: #6e6e6e;
    border-radius: 3px;
  }
}
```
