### ISSUE TITLE
Style "overflow: visible" breaks scrolling

### ISSUE THREAD

**Issue by cidevant** [bvaughn/react-window#594]
I programatically scroll list, so I dont need scrollbars. But every item in list can have shadow, which is hidden if List is doesnt have "overflow: visible".  But this style breaks all scrolling. 

Working (broken) example can be found here: https://codesandbox.io/s/dazzling-kepler-ru9rw?file=/index.js
To make this example working just comment "style={{ overflow: "visible" }}"

How it looks like when scrolling working (no overflow visible):
![Screenshot from 2021-09-10 12-12-28](https://user-images.githubusercontent.com/7719146/132838553-6e86875f-3a37-48eb-8ae8-7354eb751a0f.png)

How it looks like when scrolling is broken (overflow: visible)
![Screenshot from 2021-09-10 12-14-18](https://user-images.githubusercontent.com/7719146/132838670-35259bea-8075-4409-b76a-1cb0afd21736.png)

How to properly solve this issue?

**Comment by robertcorponoi** [comment]
I'm not sure if you're still having this issue but I checked out your codesandbox and got it working by hiding the scrollbar instead of adjusting the overflow.

If you remove `"style={{ overflow: "visible" }}` and add the following to the CSS, it should solve your issue:

```css
.List {
    border: 1px solid #d9dddd;
    /* Firefox */
    scrollbar-width: none;
}

/* Chromium */
.List::-webkit-scrollbar {
    display: none;
}
```
